---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provider-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-kubelet-config
  namespace: kube-system
data:
  provider.yaml: |
    apiVersion: v1
    cloud:
      aws:
        region: "us-east-1"
        accessKeyID: ""
        secretAccessKey: ""
        imageOwnerID: 689494258501
    etcd:
      internal:
        dataDir: /opt/kip/data
    cells:
      bootImageTags:
        company: elotl
        product: kipdev
      defaultInstanceType: "t3.nano"
      defaultVolumeSize: "20G"
      nametag: virtual-kubelet
      itzo:
        url: https://itzo-kip-dev-download.s3.amazonaws.com
        version: latest
    kubelet:
      cpu: "20"
      memory: "512Gi"
      pods: "200"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vk-network-agent
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: vk-network-agent
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - namespaces
      - pods
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - list
      - get
      - watch
  - apiGroups:
    - extensions
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: vk-network-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vk-network-agent
subjects:
- kind: ServiceAccount
  name: vk-network-agent
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vk-network-agent
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vk-network-agent
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtual-kubelet
rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
    - authorization.k8s.io
    resources:
      - localsubjectaccessreviews
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
    - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - nodes/status
    verbs:
      - patch
      - update
  - apiGroups:
    - ""
    resources:
      - nodes
    verbs:
      - patch
      - update
  - apiGroups:
    - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - create
      - delete
  - apiGroups:
    - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
  - apiGroups:
    - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
    - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
  - apiGroups:
    - ""
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups:
    - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
    - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
  - apiGroups:
    - ""
    resources:
      - persistentvolumeclaims/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
    - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
    - storage.k8s.io
    resources:
      - csidrivers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - create
      - delete
      - get
      - patch
      - update
  - apiGroups:
    - node.k8s.io
    resources:
      - runtimeclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - kip.elotl.co
    resources:
      - cells
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
    - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - deletecollection
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
roleRef:
  kind: ClusterRole
  name: virtual-kubelet
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: virtual-kubelet
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: virtual-kubelet
  name: virtual-kubelet
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-kubelet
  template:
    metadata:
      labels:
        app: virtual-kubelet
    spec:
      containers:
      - command:
        - /virtual-kubelet
        - --provider
        - cloud-instance-provider
        - --provider-config
        - /etc/virtual-kubelet/provider.yaml
        - --network-agent-secret
        - kube-system/vk-network-agent
        - --disable-taint
        - --klog.logtostderr
        - --klog.v=5
        image: elotl/virtual-kubelet:dev
        imagePullPolicy: Always
        name: virtual-kubelet
        env:
        - name: KUBELET_PORT
          value: "10666"
        - name: APISERVER_CERT_LOCATION
          value: /etc/kubelet-pki/kubelet.crt
        - name: APISERVER_KEY_LOCATION
          value: /etc/kubelet-pki/kubelet.key
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: data
          mountPath: /opt/kip/data
        - name: provider-yaml
          mountPath: /etc/virtual-kubelet
        - name: kubelet-pki
          mountPath: /etc/kubelet-pki
        - name: xtables-lock
          mountPath: /run/xtables.lock
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: virtual-kubelet
      hostNetwork: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: provider-data
      - name: kubelet-pki
        hostPath:
          path: /var/lib/kubelet/pki
          type: Directory
      - name: provider-yaml
        configMap:
          name: virtual-kubelet-config
          items:
          - key: provider.yaml
            path: provider.yaml
            mode: 0600
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: ""
