---
apiVersion: v1
kind: ConfigMap
metadata:
  name: virtual-kubelet-config
  namespace: kube-system
data:
  server.yml: |
    apiVersion: v1
    cloud:
      aws:
        region: "us-east-1"
        accessKeyID: ""
        secretAccessKey: ""
        imageOwnerID: 689494258501
    etcd:
      internal:
        dataDir: /opt/milpa/data
    cells:
      defaultInstanceType: "t3.nano"
      defaultVolumeSize: "20G"
    kubelet:
      cpu: "20"
      memory: "512Gi"
      pods: "200"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtual-kubelet
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
roleRef:
  kind: ClusterRole
  name: system:node
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: virtual-kubelet
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: virtual-kubelet
  name: virtual-kubelet
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-kubelet
  template:
    metadata:
      labels:
        app: virtual-kubelet
    spec:
      containers:
      - command:
        - /virtual-kubelet
        - --provider
        - cloud-instance-provider
        - --provider-config
        - /etc/virtual-kubelet/server.yml
        image: elotl/virtual-kubelet:dev
        imagePullPolicy: Always
        name: virtual-kubelet
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        volumeMounts:
        - name: server-yml
          mountPath: /etc/virtual-kubelet
      restartPolicy: Always
      serviceAccountName: virtual-kubelet
      hostNetwork: true
      volumes:
      - name: server-yml
        configMap:
          name: virtual-kubelet-config
          items:
          - key: server.yml
            path: server.yml
            mode: 0600
